services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hapi-fhir-postgres:5432/fhirdb"
      SPRING_DATASOURCE_USERNAME: "fhiruser"
      SPRING_DATASOURCE_PASSWORD: "fhirpass"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      APP_JWT_SECRET: "MySecretKeyForJWTAuthenticationThatIsAtLeast256BitsLongForHS256Algorithm"
      APP_JWT_EXPIRATION: "86400000"
    ports:
      - "8080:8080"
    depends_on:
      hapi-fhir-postgres:
        condition: service_healthy
  hapi-fhir-postgres:
    image: postgres:16-alpine
    container_name: hapi-fhir-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "fhirdb"
      POSTGRES_USER: "fhiruser"
      POSTGRES_PASSWORD: "fhirpass"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U fhiruser -d fhirdb' || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data

volumes:
  hapi-fhir-postgres:
